# docker network create ph-net

# docker volume create ph-pg-data
# docker volume create server-node-modules
# docker volume create server-logs
# docker volume create client-node-modules

# docker run -d --name ph-db --network ph-net -e POSTGRES_USER=postgres -e POSTGRES_PASSWORD=secret123 -e POSTGRES_DB=ph_health -v ph-pg-data:/var/lib/postgresql/data postgres:16-alpine


services:
  ph-db:
    image: postgres:16-alpine
    container_name: ph-db
    networks:
      - ph-net
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret123
      - POSTGRES_DB=ph_health
    volumes:
      - ph-pg-data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ph_health"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s


# docker run -d --name ph-db --network ph-net -e POSTGRES_USER=postgres -e POSTGRES_PASSWORD=secret123 -e POSTGRES_DB=ph_health -v ph-pg-data:/var/lib/postgresql/data postgres:16-alpine

# docker build -t ph-server-dev ./server
# MSYS_NO_PATHCONV=1 docker run -d --name ph-server --network ph-net --env-file ./server/.env -e CHOKIDAR_USEPOLLING=1 -e CHOKIDAR_INTERVAL=300 -p 5000:5000 -v "$PWD/server:/app" -v server-node-modules:/app/node_modules -v server-logs:/app/logs -w /app ph-server-dev sh -lc "CI=true pnpm install && pnpm generate && pnpm dev"
# docker exec -it ph-server sh -lc "pnpm exec prisma migrate deploy"

  ph-server:
    container_name: ph-server
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      ph-db:
        condition: service_healthy
    networks:
      - ph-net
    env_file:
      - ./server/.env
    environment:
      CHOKIDAR_USEPOLLING: "1"
      CHOKIDAR_INTERVAL: "300"
    ports: 
      - "5000:5000"  
    working_dir: /app  
    volumes:
      - ./server:/app
      - server-node-modules:/app/node_modules
      - server-logs:/app/logs
    command: sh -lc "CI=true pnpm install && pnpm generate && pnpm prisma migrate deploy && pnpm dev"


# MSYS_NO_PATHCONV=1 docker run -d --name ph-client --network ph-net --env-file ./client/.env -e CHOKIDAR_USEPOLLING=1 -e CHOKIDAR_INTERVAL=300 -e WATCHPACK_POLLING=true -p 3000:3000 -v "$PWD/client:/app" -v client-node-modules:/app/node_modules -w /app ph-client-dev sh -lc "CI=true pnpm install && pnpm exec next dev --webpack -H 0.0.0.0 -p 3000"


  ph-client: 
    container_name: ph-client
    build: 
      context: ./client
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      ph-server:
        condition: service_started
    networks:
      - ph-net
    env_file:
      - ./client/.env.local
    environment:
      CHOKIDAR_USEPOLLING: "1"
      CHOKIDAR_INTERVAL: "300"
      WATCHPACK_POLLING: "true"
    ports: 
      - "3000:3000"
    volumes:
      - ./client:/app
      - client-node-modules:/app/node_modules
    working_dir: /app
    command: sh -lc "CI=true pnpm install && pnpm exec next dev --webpack -H 0.0.0.0 -p 3000"



networks:
  ph-net:
    driver: bridge

volumes:
  ph-pg-data:
  server-node-modules:
  server-logs:
  client-node-modules:





